baseURL = "http://carim.ar/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
defaultContentLanguageInSubdir = false
title = "Carim Fadil"
uglyURLs = false

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.3.0"

[params.cdn]
  # Prefer self-hosted third-party libraries shipped with LoveIt v0.3.0.
  # Remove Mermaid CDN override to avoid loading ESM-only builds that do not expose window.mermaid.
  # To re-enable a CDN, set to a UMD/IIFE compatible build (e.g., mermaid 9.x).
  data = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = "Blog Posts"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "Browse by Tags"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Browse by Categories"
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

[params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Carim's Place"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

# Footer config
[params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2021
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # LoveIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # LoveIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "carimfadil@gmail.com"
      # URL of avatar shown in home page
      avatarURL = "https://s.gravatar.com/avatar/a3ebaf58303a25bfa202357090ff93ea?s=80"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "I'm Carim Fadil, DevOps Engineer"
      # subtitle shown in home page
      subtitle = "I'm interested in cloud architecture, infrastructure optimization, pipeline automation, biking and nature. Feel free to contact me!"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    Linkedin = "carimfadil"
    GitHub = "carim07"
    #Telegram = "carim07"
    Lastfm = "carim07"
    Strava = "carimfadil"
    Email = "carimfadil@gmail.com"
    #RSS = true # LoveIt NEW | 0.2.0
    #Spotify = "carim07"
    #Twitter = "xxxx"
    #Instagram = "xxxx"
    #Facebook = "xxxx"
    #Medium = ""
    #Gitlab = ""
    #Youtubelegacy = ""
    #Youtubecustom = ""
    #Youtubechannel = ""
    #Tumblr = ""
    #Quora = "" 
    #Pinterest = ""
    #Reddit = ""
    #Codepen = ""
    #FreeCodeCamp = ""
    #Bitbucket = "carim07"
    #Stackoverflow = ""
    #Weibo = ""
    #Odnoklassniki = ""
    #VK = ""
    #Flickr = ""
    #Xing = ""
    #Snapchat = ""
    #Soundcloud = "" 
    #Bandcamp = ""
    #Paypal = ""
    #Fivehundredpx = ""
    #Mix = ""
    #Goodreads = ""
    #Foursquare = ""
    #Hackernews = ""
    #Kickstarter = ""
    #Patreon = ""
    #Steam = ""
    #Twitch = ""
    #Whatsapp = ""
    #Zhihu = ""
    #Douban = ""
    #Angellist = ""
    #Slidershare = ""
    #Jsfiddle = ""
    #Deviantart = ""
    #Behance = ""
    #Dribbble = ""
    #Wordpress = ""
    #Vine = ""
    #Googlescholar = ""
    #Researchgate = ""
    #Mastodon = ""
    #Thingiverse = ""
    #Devto = ""
    #Gitea = ""
    #XMPP = ""
    #Matrix = ""
    #Bilibili = ""

[params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 50
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

# Comments (LoveIt v0.3.0)
[params.page.comment]
    enable = true
    [params.page.comment.giscus]
        enable = true
        repo = "carim07/carim-web"
        repoId = "MDEwOlJlcG9zaXRvcnkzODk0NDI2MzM "
        category = "Blog Comments"
        categoryId = "DIC_kwDOFzZsSc4CxVNZ"
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top"
        lightTheme = "light"
        darkTheme = "transparent_dark"
    
[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1

  [languages.es]
    languageName = "Español"
    languageCode = "es"
    weight = 2

  # Spanish menu labels
  [languages.es.menu]
    [[languages.es.menu.main]]
      identifier = "posts"
      name = "Artículos"
      url = "/posts/"
      title = "Artículos del blog"
      weight = 1
    [[languages.es.menu.main]]
      identifier = "tags"
      name = "Etiquetas"
      url = "/tags/"
      title = "Explorar por etiquetas"
      weight = 2
    [[languages.es.menu.main]]
      identifier = "categories"
      name = "Categorías"
      url = "/categories/"
      title = "Explorar por categorías"
      weight = 3

  # Spanish localized home profile
  [languages.es.params.home.profile]
    title = "Soy Carim Fadil, Ingeniero DevOps"
    subtitle = "Interesado en arquitectura en la nube, optimización de infraestructura, automatización de pipelines, el ciclismo y la naturaleza. ¡Contáctame!"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "carim-s3-prod"
URL = "s3://carim.ar?region=us-east-1"
cloudFrontDistributionID = "E38WXPLVGOJ43A"
